santa/urls.py
from django.conf.urls import url
from . import views

app_name = 'santa'

urlpatterns = [
    url(r'^$', views.HomepageView.as_view(), name='home'),
    url(r'^create/$', views.ListCreationView.as_view(), name='create'),
    url(r'^created/(?P<slug>[\w-]+)$', views.ListCreatedView.as_view(), name='created'),
    url(r'^signup/(?P<secure_hash>[a-f0-9]{12})/(?P<slug>[\w-]+)/$', views.SignupView.as_view(), name='signup'),
    url(r'^review/(?P<secure_hash>[a-f0-9]{12})/(?P<slug>[\w-]+)/$', views.ReviewListView.as_view(), name='review'),
    url(r'^close/(?P<secure_hash>[a-f0-9]{12})/(?P<slug>[\w-]+)/$', views.CloseListView.as_view(), name='close'),
    url(r'^thanks/$', views.ThanksView.as_view(), name='thanks'),
]

secret_santa/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('santa.urls'), name='santa'),
]

santa/models.py
import random
import itertools
import hashlib

from django.db import models
from django.core.mail import send_mass_mail, send_mail
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from django.contrib.sites.shortcuts import get_current_site

from . import creation_email_subject, creation_email_content


class SantaList(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    organiser_email = models.EmailField(max_length=200)
    email_subject = models.CharField(max_length=200)
    email_content = models.TextField()

    # For people to sign up
    secure_hash_signup = models.CharField(max_length=12, unique=True, null=True)
    # For the organiser to review/close
    secure_hash_review = models.CharField(max_length=12, unique=True, null=True)

    def __str__(self):
        return "{0}".format(self.name)

    def get_signup_url(self, request):
        current_site = get_current_site(request)
        secure_hash = self.secure_hash_signup
        slug = self.slug
        signup_path = reverse('santa:signup', kwargs={'secure_hash': secure_hash, 'slug': slug})
        return "{0}{1}".format(current_site.domain, signup_path)

    def get_review_url(self, request):
        current_site = get_current_site(request)
        secure_hash = self.secure_hash_review
        slug = self.slug
        review_path = reverse('santa:review', kwargs={'secure_hash': secure_hash, 'slug': slug})
        return "{0}{1}".format(current_site.domain, review_path)

    def send_creation_email(self, request):
        signup_url = self.get_signup_url(request)
        review_url = self.get_review_url(request)
        send_mail(
            creation_email_subject,
            creation_email_content.format(signup_url, review_url),
            settings.DEFAULT_FROM_EMAIL,
            [self.organiser_email]
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        orig_slug = self.slug
        for i in itertools.count(1):
            if not SantaList.objects.exclude(pk=self.pk).filter(slug=self.slug).exists():
                break

            self.slug = '%s-%d' % (orig_slug, i)

        super().save(*args, **kwargs)

        if not self.secure_hash_signup or not self.secure_hash_review:
            token = "{0}{1}".format(self.pk, self.slug)
            md5 = hashlib.md5(token.encode('utf-8')).hexdigest()
            self.secure_hash_signup = md5[:12]
            self.secure_hash_review = md5[12:24]
            self.save()

    def get_email_data(self, pairs):
        data_list = []
        for giver, receiver in pairs:
            email_to = ["Santa's Little Helper <{0}>".format(giver.email)]
            content = self.email_content.format(giver=giver, receiver=receiver)
            subject = self.email_subject.format(giver=giver, receiver=receiver)
            data_item = (subject, content, settings.DEFAULT_FROM_EMAIL, email_to)
            data_list.append(data_item)

        return tuple(data_list)

    def shuffle_recipients(self):
        matches = {}
        # Get all the people on this list, and shuffle them
        person_list = list(self.person_set.all())
        random.shuffle(person_list)

        # Now that the list is randomised, just match each person, to the next person in the list
        for i, person in enumerate(person_list):
            try:
                matches[person] = person_list[i+1]
            except IndexError:
                # This is the last person on the list, so match them to the first person, who's currently unmatched
                matches[person] = person_list[0]

        # Return a tuple of ((giver, receiver,) ...)
        return matches.items()

    def finish_list(self):
        pairs = self.shuffle_recipients()
        data = self.get_email_data(pairs)
        send_mass_mail(data)
        self.person_set.all().delete()
        self.delete()


class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    santa_list = models.ForeignKey(SantaList)

    @property
    def name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __str__(self):
        return self.name

santa/forms.py
from django import forms
from .models import SantaList, Person


class PersonAddingForm(forms.ModelForm):

    class Meta:
        model = Person
        exclude = []
        widgets = {'santa_list': forms.HiddenInput()}
        labels = {
            "email": "Your email"
        }


class ListCreationForm(forms.ModelForm):

    class Meta:
        model = SantaList
        exclude = ['slug', 'secure_hash_signup', 'secure_hash_review']
        labels = {
            "name": "List name",
            "organiser_email": "Your email"
        }

santa/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, DetailView
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from django.conf import settings

from . import default_email_content_template, default_email_subject_template
from .forms import ListCreationForm, PersonAddingForm
from .models import SantaList, Person


class HomepageView(TemplateView):
    template_name = 'santa/homepage.html'


class ListCreationView(CreateView):
    model = SantaList
    template_name_suffix = '_add'
    form_class = ListCreationForm

    def get_success_url(self):
        return reverse('santa:created', kwargs={'slug': self.object.slug})

    def get_initial(self):
        return {
            'email_content': default_email_content_template,
            'email_subject': default_email_subject_template
        }

    def form_valid(self, form):
        resp = super().form_valid(form)
        self.object.send_creation_email(self.request)
        return resp


class ListCreatedView(DetailView):
    template_name = 'santa/created.html'
    model = SantaList

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['signup_url'] = self.object.get_signup_url(self.request)
        context['review_url'] = self.object.get_review_url(self.request)
        return context


class ReviewListView(TemplateView):
    template_name = 'santa/review.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        slug = self.kwargs.get('slug')
        secure_hash = self.kwargs.get('secure_hash')
        context['santa_list'] = get_object_or_404(SantaList, slug=slug, secure_hash_review=secure_hash)
        return context


class CloseListView(ReviewListView):
    template_name = 'santa/close.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        santa_list = context.pop('santa_list')
        santa_list.finish_list()
        return context


class SignupView(CreateView):
    model = Person
    template_name_suffix = '_add'
    form_class = PersonAddingForm
    success_url = '/thanks/'

    def get_initial(self):
        slug = self.kwargs.get('slug')
        secure_hash = self.kwargs.get('secure_hash')
        self.santa_list = get_object_or_404(SantaList, slug=slug, secure_hash_signup=secure_hash)
        return {'santa_list': self.santa_list}

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['santa_list'] = self.santa_list
        return context


class ThanksView(TemplateView):
    template_name = 'santa/thanks.html'

santa/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- My styles for the app -->
    <link href="{% static "css/santa.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extrastyle %}{% endblock %}
    {% block extra_head %}{% endblock %}
  </head>
  <body class="{% block bodyclass %}{% endblock %}">
    <header>
      {% block header %}{% endblock %}
    </header>

    <main>
      {% block content %}{% endblock %}
    </main>

    <footer>
      {% block footer %}{% endblock %}
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

santa/templates/santa/close.html
{% extends "base.html" %}

{% block content %}
    <h1>Thank you, your Secret Santa list has been closed!</h1>
    <p>All participants should now have their email from Santa</p>
{% endblock %}

santa/templates/santa/created.html
{% extends "base.html" %}

{% block content %}
    <h1>Thank you, your Secret Santa list has been created</h1>
    <h2>NOTE: You are not yet signed up to your own list!</h2>
    <p>To <a href="{% url 'santa:signup' object.secure_hash_signup object.slug %}">sign up to this list</a> as a participant, and to get others to participate, please use:<br/><a href="{% url 'santa:signup' object.secure_hash_signup object.slug %}">{{ signup_url }}</a></p>
    <p>To <a href="{% url 'santa:review' object.secure_hash_review object.slug %}">review and close</a> your list, triggering Santa to send out emails to all poeple that signed up, please use:<br/><a href="{% url 'santa:review' object.secure_hash_review object.slug %}">{{ review_url }}</a></p>
{% endblock %}

santa/templates/santa/homepage.html
{% extends "base.html" %}

{% block content %}
    <h1>Secret Santa</h1>
    <p><a href="{% url 'santa:create' %}">Create a new Secret Santa list</a></p>
{% endblock %}

santa/templates/santa/person_add.html
{% extends "base.html" %}

{% block content %}
    <h1>Signup to Secret Santa</h1>
    <div class="instructions">
        <p>Fill in this form to participate in the Secret Santa list: {{ santa_list.name }}</p>
        <p>Just provide your full name and email address, and when the list is closed, you will receive an email</p>
    </div>
    <form method="post" action="{{ request.path }}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Submit' />
    </form>
{% endblock %}

santa/templates/santa/review.html
{% extends "base.html" %}

{% block content %}
    <h1>You have set up your Secret Santa list</h1>
    <p>There are currently {{ santa_list.person_set.count }} people signed up</p>
    <p>When you are ready, <a href="{% url 'santa:close' santa_list.secure_hash_review santa_list.slug %}">close the list</a>, and Santa will email all participants</p>
{% endblock %}

santa/templates/santa/santalist_add.html
{% extends "base.html" %}

{% block content %}
    <h1>Create new Secret Santa List</h1>
    <div class="instructions">
        <p>Fill in this form to create your Secret Santa list</p>
        <ul>
            <li>Provide a fiendly name for you list, which will appear in URLs for people to sign up to it.</li>
            <li>Your own email address is needed so that you can be sent the links required to signup and administer your list</li>
            <li>Customise the email subject and body that will be sent to participants
                <ul>
                    <li>Use {giver} to substite the Giver's name</li>
                    <li>Use {receiver} to substitue the Receiver's name</li>
                </ul>
            </li>
        </ul>
    </div>
    <form method="post" action="{% url 'santa:create' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Submit' />
    </form>
{% endblock %}

santa/templates/santa/thanks.html
{% extends "base.html" %}

{% block content %}
    <h1>Thank you!</h1>
    <p>You are now signed up to this Secret Santa list!</p>
{% endblock %}